import {
  FIREBASE_DATABASE_API_KEY,
  FIREBASE_AUTH_URL,
  FIREBASE_DATABASE_URL,
  FIREBASE_STORAGE_URL,
} from '@env'

export default {
  FIREBASE_DATABASE_API_KEY,
  FIREBASE_AUTH_URL,
  FIREBASE_DATABASE_URL,
  FIREBASE_STORAGE_URL,
}
