import {
  FIREBASE_DATABASE_API_KEY,
  FIREBASE_AUTH_URL,
  FIREBASE_DATABASE_URL,
  FIREBASE_STORAGE_URL,
  KAKAO_BOOK_SEARCH_API_KEY,
} from '@env'

export default {
  FIREBASE_DATABASE_API_KEY,
  FIREBASE_AUTH_URL,
  FIREBASE_DATABASE_URL,
  FIREBASE_STORAGE_URL,
  KAKAO_BOOK_SEARCH_API_KEY,
}
