export const BASE_URL = 'http://3.37.129.186/apis/v1'
export const LOGIN = '/auth/login'
export const SIGNUP = '/auth/signUp'
export const SEARCH_BOOK = '/books'
export const MAKE_SCRAPBOOK = '/scrapbook'
export const SCRAPBOOKS = '/scrapbooks'
export const ME = '/user/me'